version: "3"
services:
  mysqlsrv:
    #    platform: linux/x86_64
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cripto_local"
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
